### ISSUE TITLE
Update Snowplow Android lib to 2.0 

### ISSUE THREAD

**Issue by koga187** [SuaMusica/flutter_plugins#97]
Update the Android dependency following the docs.

https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/mobile-trackers/migration-guides/migration-guide-for-snowplow-android-tracker-sdk-from-version-1-x-to-2-0/

**Comment by nferreira** [comment]
Oi @koga187,

Eu to com problema sobre essas issues pois as APIs mudaram completamente.
Tem coisa que eu não to achando.
Tem método que era de uma forma e agora é de outro. Por exemplo, antes um Tracker tinha uma subject e você poderia mudar o Subject e setar:

private void setUserId(final MethodChannel.Result result, String userId) {
        Subject sbj = tracker.getSubject();
        sbj.setUserId(userId);
        tracker.setSubject(sbj);
        result.success(true);
    }
Agora não tem mais isso. Não sei se é porque não precisa mais., tipo posso fazer assim:

private void setUserId(final MethodChannel.Result result, String userId) {
        SubjectController sbj = tracker.getSubject();
        sbj.setUserId(userId);
        result.success(true);
    }
Daí to lendo que ler o código dos caras para entender.

@atrope e @koga187 como faço para ter uma conta com acesso ao Snowplow pra ver o que chega lá?
